version: "3"
services:
  open-stack-service:
    image: open-stack-service:latest
    ports:
      - "8080:8080"
    environment:
      - CONFIG_SERVER_URL=http://config-server:8888
      - EUREKA_URI=http://eureka:8761/eureka
networks:
  default:
    external:
      name: open-stack
